// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJp9zxMmkC7cmzBOOB3_ssnMeJePJn8s0',
    appId: '1:1034003209586:web:989217fd76a54876b411eb',
    messagingSenderId: '1034003209586',
    projectId: 'flutter18firebase',
    authDomain: 'flutter18firebase.firebaseapp.com',
    storageBucket: 'flutter18firebase.appspot.com',
    measurementId: 'G-5NRE0RT0CN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZpsL6HFWj-0a5CB6mLbEC36rRUlZA_mI',
    appId: '1:1034003209586:android:958aa0347a32b53ab411eb',
    messagingSenderId: '1034003209586',
    projectId: 'flutter18firebase',
    storageBucket: 'flutter18firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz6FR4ynJeKCfCJrtHE7OAKdvu6DerZyQ',
    appId: '1:1034003209586:ios:52187d07a522030bb411eb',
    messagingSenderId: '1034003209586',
    projectId: 'flutter18firebase',
    storageBucket: 'flutter18firebase.appspot.com',
    iosClientId: '1034003209586-ikpjdd7hpgn5o2ncqik6idbpgpf8n8ag.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutter18Firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz6FR4ynJeKCfCJrtHE7OAKdvu6DerZyQ',
    appId: '1:1034003209586:ios:52187d07a522030bb411eb',
    messagingSenderId: '1034003209586',
    projectId: 'flutter18firebase',
    storageBucket: 'flutter18firebase.appspot.com',
    iosClientId: '1034003209586-ikpjdd7hpgn5o2ncqik6idbpgpf8n8ag.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutter18Firebase',
  );
}
